packages:
  - 'apps/*'
  - 'apps/*/backend'
  - 'apps/*/frontend'
  - 'packages/*'
allowBuilds:
  '@prisma/engines': false
  '@scarf/scarf': true
  '@tailwindcss/oxide': true
  bcrypt: true
  prisma: false
  sharp: true
  unrs-resolver: true
